"""
Django settings for LT project.

Generated by 'django-admin startproject' using Django 2.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'DONE/static/js', 'serviceworker.js')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@n35^kkz7nuzso1(5kpf0i^@&1nc0^-1ysjz#4@jztro^c!fro'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['jlochran.pythonanywhere.com', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'DONE',
    'accounts',
    'pwa',
    'resources',
    'multiselectfield'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'LT.middleware.LoginRequiredMiddleware',
]

ROOT_URLCONF = 'LT.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['LT/templates'],
        # 'DIRS': ['lochtek/LT/templates'], change this to deploy


        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LT.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'LT/static/')

]
STATIC_ROOT = '/home/jlochran/lochtek/static'
#STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

MEDIA_URL = '/media/'



# try:
#     from .local_settings import *
# except ImportError:
#     pass

#test email configuratuon
# EMAIL_HOST = 'localhost'
# EMAIL_PORT = 1025

# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_HOST_USER = 'sample@gmail.com'
# EMAIL_HOST_PASSWORD = 'sample'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True

PWA_APP_NAME = 'DONE'
PWA_APP_DESCRIPTION = "An Application to get things DONE!"
PWA_APP_THEME_COLOR = '#0A0302'
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
PWA_APP_ICONS = [
    {
        'src': '/static/images/icons/DONE_PWA-72x72.png',
        'sizes': '72x72'
    },
    {
        'src': '/static/images/icons/DONE_PWA-96x96.png',
        'sizes': '96x96'
    },
    {
        'src': '/static/images/icons/DONE_PWA-128x128.png',
        'sizes': '128x128'
    },
    {
        'src': '/static/images/icons/DONE_PWA-144x144.png',
        'sizes': '144x144'
    },
    {
        'src': '/static/images/icons/DONE_PWA-152x152.png',
        'sizes': '152x152'
    },
    {
        'src': '/static/images/icons/DONE_PWA-192x192.png',
        'sizes': '192x192'
    },
    {
        'src': '/static/images/icons/DONE_PWA-384x384.png',
        'sizes': '384x384'
    },
    {
        'src': '/static/images/icons/DONE_PWA-512x512.png',
        'sizes': '512x512'
    }
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'en-US'

# try:
#     from .local_settings import *
# except ImportError:
#     pass
# =======
EMAIL_HOST = 'smtp.gmail.com'

EMAIL_HOST_USER ='replaceme'
EMAIL_HOST_PASSWORD ='example'


EMAIL_PORT = 587
EMAIL_USE_TLS = True

LOGIN_REDIRECT_URL = '/dashboard'
