# Generated by Django 2.0.4 on 2018-08-29 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='description')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('date_changed', models.DateTimeField(auto_now=True, verbose_name='changed date')),
                ('type', models.CharField(choices=[('Architectural', 'Architectural'), ('Electrical', 'Electrical'), ('Mechanical', 'Mechanical'), ('Structural build or Demo', 'Structural build or Demo'), ('Multi-discipline', 'Multi-discipline')], default='Architectural', max_length=100, verbose_name='Project Type')),
                ('location', models.TextField(blank=True, max_length=500, null=True, verbose_name='location')),
                ('support', models.CharField(choices=[('Project Manager', 'Project Manager'), ('Construction Manager', 'Construction Manager'), ('Admin', 'Admin')], default='Project Manager', max_length=100, verbose_name='Support Needed')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('contact_me', models.CharField(choices=[('Email', 'Email'), ('Call', 'Call'), ('Both', 'Both')], default='Email', max_length=100, verbose_name='Best Way to Contact Me')),
                ('timeframe', models.CharField(choices=[('Less than 2 weeks', 'Less than 2 Weeks'), ('1 month', '1 Month'), ('1 to 3 months', '1 to 3 months')], default='Weeks', max_length=100, verbose_name='When do you need help')),
                ('pub_date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
