# Generated by Django 2.0.4 on 2018-08-30 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DONE', '0002_auto_20180829_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='pub_date',
        ),
    ]
