# Generated by Django 2.0.2 on 2018-10-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DONE', '0004_auto_20180829_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estimated_time',
            field=models.CharField(choices=[('Less than 1 month', 'Less than 1 month'), ('1 month', '1 month'), ('3 months', '3 month'), ('6 months', '6 month'), ('12 months', '12 month')], default='1 month', max_length=100, verbose_name='ESTIMATED_TIME'),
        ),
        migrations.AddField(
            model_name='project',
            name='paymentterms',
            field=models.CharField(choices=[('Net 30 days', 'Net 30 days'), ('Net 15 days', '15 days'), ('Net 45 days', '45 days'), ('Net 90 days', '90 days'), ('Net 120 days', '120 days'), ('Net 180 days', '180 days')], default='Net 30 days ', max_length=100, verbose_name='PAYMENTTERMS'),
        ),
        migrations.AddField(
            model_name='project',
            name='sitetime',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('1/2 time', '1/2 time'), ('1/4 time', '1/4 time')], default='Full-time', max_length=100, verbose_name='SITETIME'),
        ),
    ]
