# Generated by Django 2.0.2 on 2018-10-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DONE', '0006_auto_20181010_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='baserate',
            field=models.PositiveSmallIntegerField(blank=True, default=920, null=True),
        ),
    ]
