# Generated by Django 2.0.2 on 2018-10-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DONE', '0008_auto_20181010_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='paymentterms',
            field=models.CharField(choices=[('Net 30 days', 'Net 30 days'), ('Net 15 days', 'Net 15 days'), ('Net 45 days', 'Net 45 days'), ('Net 90 days', 'Net 90 days'), ('Net 120 days', 'Net 120 days'), ('Net 180 days', 'Net 180 days')], default='Net 30 days ', max_length=100, verbose_name='Payment terms'),
        ),
    ]
