# Generated by Django 2.0.2 on 2018-10-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DONE', '0010_auto_20181010_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='estimated_time',
            field=models.CharField(choices=[('Less than 1 month', 'Less than 1 month'), ('1 month', '1 month'), ('3 months', '3 months'), ('6 months', '6 months'), ('12 months', '12 months')], default='1 month', max_length=100, verbose_name='Estimated project duration'),
        ),
    ]
