# Generated by Django 2.0.2 on 2018-10-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DONE', '0011_auto_20181010_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sitetime',
            field=models.CharField(choices=[('Onsite', 'Onsite'), ('Offsite', 'Offsite'), ('Both', 'Both')], default='Onsite', max_length=100, verbose_name='Support Location'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
