# Generated by Django 2.0.2 on 2018-12-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DONE', '0012_auto_20181012_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='support',
            field=models.CharField(choices=[('Project Manager', 'Project Manager'), ('Construction Manager', 'Construction Manager'), ('Admin', 'Admin'), ('Technical Sales', 'Technical Sales')], default='Project Manager', max_length=100, verbose_name='Support Needed'),
        ),
    ]
