# Generated by Django 2.0.2 on 2019-02-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DONE', '0014_auto_20190213_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='paymentterms',
            field=models.CharField(choices=[('Net 30 days', 'Net 30 days'), ('Net 15 days', 'Net 15 days'), ('Net 45 days', 'Net 45 days'), ('Net 90 days', 'Net 90 days'), ('Net 120 days', 'Net 120 days')], default='Net 30 days ', max_length=100, verbose_name='Payment terms'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Architectural', 'Architectural'), ('Electrical - Telecom', 'Electrical - Telecom'), ('Engineering', 'Engineering'), ('Mechanical', 'Mechanical'), ('Structural', 'Structural'), ('Environmental', 'Environmental'), ('Multi-discipline', 'Multi-discipline')], default='Architectural', max_length=100, verbose_name='Project Type'),
        ),
    ]
