# Generated by Django 2.0.4 on 2018-09-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180904_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pemail',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
