# Generated by Django 2.0.4 on 2018-09-04 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_pemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pemail',
        ),
    ]
