# Generated by Django 2.0.4 on 2018-09-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180904_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.CharField(default='', max_length=100),
        ),
    ]
