# Generated by Django 2.0.4 on 2018-09-05 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180905_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='jobtitle',
            new_name='title',
        ),
    ]
