# Generated by Django 2.0.2 on 2019-01-17 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('date_changed', models.DateTimeField(auto_now=True, verbose_name='changed date')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Street')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('zip', models.CharField(blank=True, max_length=100, null=True, verbose_name='Zip code')),
                ('work_exp', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Years of professional experience')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('proficiency', models.CharField(choices=[('Project Management', 'Project Management'), ('Construction Management', 'Construction Management'), ('Architectural', 'Architectural'), ('Mechanical', 'Mechanical'), ('Electrical', 'Electrical'), ('Construction', 'Construction'), ('Engineering', 'Engineering'), ('Aviation', 'Aviation'), ('R&D', 'R&D'), ('Power / Energy', 'Power / Energy'), ('Manufacturing', 'Manufacturing'), ('Process', 'Process'), ('Environmental', 'Environmental'), ('Maritime / Marine', 'Maritime / Marine'), ('Military', 'Military'), ('Multidiscipline engineering / construction', 'Multidiscipline engineering / construction')], default='Project Management', max_length=100, verbose_name='proficiency')),
                ('distance', models.CharField(choices=[('< 10 miles', '< 10 miles'), ('10 to 20 miles', '10 to 20 miles'), ('> 20 miles', '> 20 miles'), ('Unlimited with expenses', 'Unlimited with expenses')], default='Unlimited with expenses', max_length=100, verbose_name='Travel Distance')),
                ('max_days', models.PositiveSmallIntegerField(blank=True, default=5, null=True, verbose_name='Maximum nunmber of work days per week')),
                ('max_hours', models.PositiveSmallIntegerField(blank=True, default=8, null=True, verbose_name='Maximum work hours per day')),
                ('days_available', models.CharField(choices=[('Monday to Friday', 'Monday to Friday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday to Friday', max_length=100, verbose_name='Days available')),
                ('rate', models.PositiveSmallIntegerField(blank=True, default=50, null=True, verbose_name='Rate')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
