# Generated by Django 2.0.2 on 2019-01-22 18:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20190122_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='days_available',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('monday_friday', 'Monday to Friday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=70, verbose_name='Days available'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='distance',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('less_ten', '< 10 miles'), ('ten_twenty', '10 to 20 miles'), ('twenty_plus', '> 20 miles'), ('unlimited', 'Unlimited with expenses')], max_length=41, verbose_name='Travel Distance'),
        ),
    ]
