# Generated by Django 2.0.2 on 2019-02-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20190122_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/', verbose_name='Resume / CV'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='rate',
            field=models.PositiveSmallIntegerField(blank=True, default=50, null=True, verbose_name='Rate / hr'),
        ),
    ]
